config/routes.rb
Rails.application.routes.draw do
  get 'static_pages/devlog'

  root to: 'visitors#index'

  get 'static_pages/home'
  get 'static_pages/help'
  get 'static_pages/about'

  devise_for :admin_users, ActiveAdmin::Devise.config
  ActiveAdmin.routes(self)
  resources :details
  resources :libations
  devise_for :users
  resources :users
end

app/models/admin_user.rb
class AdminUser < ActiveRecord::Base
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, 
         :recoverable, :rememberable, :trackable, :validatable
end

app/models/detail.rb
class Detail < ActiveRecord::Base
  belongs_to :libation
  belongs_to :user
end

app/models/libation.rb
class Libation < ActiveRecord::Base
  has_many :details
  accepts_nested_attributes_for :details

  enum container_type: { Aluminium: 1, Glass: 2,Plastic: 3, Steel: 4, Tetra: 5, Cardboard: 6 ,Other: 7}
  enum measurement_type: { grams: 1, litres: 2, millilitres: 3, ounces: 4, unknown: 99}
  enum libation_type: { drink: 1,  juice: 2, soda: 3, tea: 4, dairy: 5, wine: 6, beer: 7, cooler: 8, spirits: 9, liqueurs:10, other:99 }
end

app/models/user.rb
class User < ActiveRecord::Base
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable

  has_many :details
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
end

app/controllers/details_controller.rb
class DetailsController < ApplicationController
  before_action :set_detail, only: [:show, :edit, :update, :destroy]

  # GET /details
  # GET /details.json
  def index
    @details = Detail.all
  end

  # GET /details/1
  # GET /details/1.json
  def show
  end

  # GET /details/new
  def new
    @detail = Detail.new
  end

  # GET /details/1/edit
  def edit
  end

  # POST /details
  # POST /details.json
  def create
    @detail = Detail.new(detail_params)

    respond_to do |format|
      if @detail.save
        format.html { redirect_to @detail, notice: 'Detail was successfully created.' }
        format.json { render :show, status: :created, location: @detail }
      else
        format.html { render :new }
        format.json { render json: @detail.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /details/1
  # PATCH/PUT /details/1.json
  def update
    respond_to do |format|
      if @detail.update(detail_params)
        format.html { redirect_to @detail, notice: 'Detail was successfully updated.' }
        format.json { render :show, status: :ok, location: @detail }
      else
        format.html { render :edit }
        format.json { render json: @detail.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /details/1
  # DELETE /details/1.json
  def destroy
    @detail.destroy
    respond_to do |format|
      format.html { redirect_to details_url, notice: 'Detail was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_detail
      @detail = Detail.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def detail_params
      params.require(:detail).permit(:libation_id, :user_id, :date_drank, :store_purchased, :city_purchased, :prov_purchased, :country_purchased, :colour, :pulp, :can_art, :can_look, :sweet, :juice, :sip_giz, :flavour, :buy_again, :carbonated, :filename, :comments)
    end
end

app/controllers/libations_controller.rb
class LibationsController < ApplicationController
  before_action :set_libation, only: [:show, :edit, :update, :destroy]

  # GET /libations
  # GET /libations.json
  def index
    @libations = Libation.all
  end

  # GET /libations/1
  # GET /libations/1.json
  def show
  end

  # GET /libations/new
  def new
    @libation = Libation.new
  end

  # GET /libations/1/edit
  def edit
  end

  # POST /libations
  # POST /libations.json
  def create
    @libation = Libation.new(libation_params)

    respond_to do |format|
      if @libation.save
        format.html { redirect_to @libation, notice: 'Libation was successfully created.' }
        format.json { render :show, status: :created, location: @libation }
      else
        format.html { render :new }
        format.json { render json: @libation.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /libations/1
  # PATCH/PUT /libations/1.json
  def update
    respond_to do |format|
      if @libation.update(libation_params)
        format.html { redirect_to @libation, notice: 'Libation was successfully updated.' }
        format.json { render :show, status: :ok, location: @libation }
      else
        format.html { render :edit }
        format.json { render json: @libation.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /libations/1
  # DELETE /libations/1.json
  def destroy
    @libation.destroy
    respond_to do |format|
      format.html { redirect_to libations_url, notice: 'Libation was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_libation
      @libation = Libation.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def libation_params
      params.require(:libation).permit(:libation_name, :measurement, :container_type, :measurement_type, :country_made, :company_name, :libation_type, :website)
    end
end

app/controllers/static_pages_controller.rb
class StaticPagesController < ApplicationController
  def about
  end

  def home
  end

  def help
  end

  def devlog
  end

end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  before_action :authenticate_user!

  def index
    @users = User.all
  end

  def show
    @user = User.find(params[:id])
    unless @user == current_user
      redirect_to :back, :alert => "Access denied."
    end
  end

end

app/controllers/visitors_controller.rb
class VisitorsController < ApplicationController

  def index
    @count =Libation.count
    @rnd =  rand(1)+@count
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/details_helper.rb
module DetailsHelper
end

app/helpers/libations_helper.rb
module LibationsHelper
end

app/helpers/static_pages_helper.rb
module StaticPagesHelper
end

app/views/details/_form.html.slim
= form_for @detail do |f|
  - if @detail.errors.any?
    #error_explanation
      h2 = "#{pluralize(@detail.errors.count, "error")} prohibited this detail from being saved:"
      ul
        - @detail.errors.full_messages.each do |message|
          li = message

  .field
    = f.label :libation_id
    = f.text_field :libation_id
  .field
    = f.label :user_id
    = f.text_field :user_id
  .field
    = f.label :date_drank
    = f.date_select :date_drank
  .field
    = f.label :store_purchased
    = f.text_field :store_purchased
  .field
    = f.label :city_purchased
    = f.text_field :city_purchased
  .field
    = f.label :prov_purchased
    = f.text_field :prov_purchased
  .field
    = f.label :country_purchased
    = f.text_field :country_purchased
  .field
    = f.label :colour
    = f.text_field :colour
  .field
    = f.label :pulp
    = f.number_field :pulp
  .field
    = f.label :can_art
    = f.number_field :can_art
  .field
    = f.label :can_look
    = f.number_field :can_look
  .field
    = f.label :sweet
    = f.number_field :sweet
  .field
    = f.label :juice
    = f.number_field :juice
  .field
    = f.label :sip_giz
    = f.number_field :sip_giz
  .field
    = f.label :flavour
    = f.number_field :flavour
  .field
    = f.label :buy_again
    = f.number_field :buy_again
  .field
    = f.label :carbonated
    = f.check_box :carbonated
  .field
    = f.label :filename
    = f.text_field :filename
  .field
    = f.label :comments
    = f.text_area :comments
  .actions = f.submit

app/views/details/edit.html.slim
h1 Editing detail

== render 'form'

= link_to 'Show', @detail
'|
= link_to 'Back', details_path

app/views/details/index.html.slim
h1 Listing details

table
  thead
    tr
      th Libation
      th Date drank
      th Store purchased
      th City purchased
      th Prov purchased
      th Country purchased
      th Colour
      th Pulp
      th Can art
      th Can look
      th Sweet
      th Juice
      th Sip giz
      th Flavour
      th Buy again
      th Carbonated
      th Filename
      th Comments
      th
      th
      th

  tbody
    - @details.each do |detail|
      tr
        td = detail.libation
        td = detail.date_drank
        td = detail.store_purchased
        td = detail.city_purchased
        td = detail.prov_purchased
        td = detail.country_purchased
        td = detail.colour
        td = detail.pulp
        td = detail.can_art
        td = detail.can_look
        td = detail.sweet
        td = detail.juice
        td = detail.sip_giz
        td = detail.flavour
        td = detail.buy_again
        td = detail.carbonated
        td = detail.filename
        td = detail.comments
        td = link_to 'Show', detail
        td = link_to 'Edit', edit_detail_path(detail)
        td = link_to 'Destroy', detail, data: {:confirm => 'Are you sure?'}, :method => :delete

br

= link_to 'New Detail', new_detail_path

app/views/details/new.html.slim
h1 New detail

== render 'form'

= link_to 'Back', details_path

app/views/details/show.html.slim
p#notice = notice

p
  strong Libation:
  = @detail.libation
p
  strong User:
  = @detail.user
p
  strong Date drank:
  = @detail.date_drank
p
  strong Store purchased:
  = @detail.store_purchased
p
  strong City purchased:
  = @detail.city_purchased
p
  strong Prov purchased:
  = @detail.prov_purchased
p
  strong Country purchased:
  = @detail.country_purchased
p
  strong Colour:
  = @detail.colour
p
  strong Pulp:
  = @detail.pulp
p
  strong Can art:
  = @detail.can_art
p
  strong Can look:
  = @detail.can_look
p
  strong Sweet:
  = @detail.sweet
p
  strong Juice:
  = @detail.juice
p
  strong Sip giz:
  = @detail.sip_giz
p
  strong Flavour:
  = @detail.flavour
p
  strong Buy again:
  = @detail.buy_again
p
  strong Carbonated:
  = @detail.carbonated
p
  strong Filename:
  = @detail.filename
p
  strong Comments:
  = @detail.comments

= link_to 'Edit', edit_detail_path(@detail)
'|
= link_to 'Back', details_path

app/views/layouts/_messages.html.slim
/ Rails flash messages styled for Bootstrap 3.0
- flash.each do |name, msg|
  - if msg.is_a?(String)
    div class="alert alert-#{name.to_s == 'notice' ? 'success' : 'danger'}"
      button.close[type="button" data-dismiss="alert" aria-hidden="true"] ×
      = content_tag :div, msg, :id => "flash_#{name}"

app/views/layouts/_nav_links_for_auth.html.erb
<% if user_signed_in? %>
  <li><%= link_to 'Edit account', edit_user_registration_path %></li>
  <li><%= link_to 'Sign out', destroy_user_session_path, :method=>'delete' %></li>
<% else %>
  <li><%= link_to 'Sign in', new_user_session_path %></li>
  <li><%= link_to 'Sign up', new_user_registration_path %></li>
<% end %>
<% if user_signed_in? %>
  <li><%= link_to 'Users', users_path %></li>
<% end %>

app/views/layouts/_navigation.html.slim
/ navigation styled for Bootstrap 3.0
nav.navbar.navbar-inverse.navbar-fixed-top
  .container
    .navbar-header
      button.navbar-toggle[type="button" data-toggle="collapse" data-target=".navbar-collapse"]
        span.sr-only Toggle navigation
        span.icon-bar
        span.icon-bar
        span.icon-bar
      = link_to 'Home', root_path, class: 'navbar-brand'
    .collapse.navbar-collapse
      ul.nav.navbar-nav
        == render 'layouts/navigation_links'

app/views/layouts/_navigation_links.html.erb
<%# add navigation links to this file %>

app/views/layouts/application.html.slim
doctype html
html
  head
    meta[name="viewport" content="width=device-width, initial-scale=1.0"]
    title
      = content_for?(:title) ? yield(:title) : 'Libations'
    meta name="description" content="#{content_for?(:description) ? yield(:description) : 'Libations'}"
    == stylesheet_link_tag "application", :media => 'all', 'data-turbolinks-track' => true
    == javascript_include_tag 'application', 'data-turbolinks-track' => true
    == csrf_meta_tags
  body
    header
      == render 'layouts/navigation'
    main[role="main"]
      == render 'layouts/messages'
      == yield

app/views/libations/_form.html.slim
= form_for @libation do |f|
  - if @libation.errors.any?
    #error_explanation
      h2 = "#{pluralize(@libation.errors.count, "error")} prohibited this libation from being saved:"
      ul
        - @libation.errors.full_messages.each do |message|
          li = message
  .field
    = f.label :libation_name
    = f.text_field :libation_name
  .field
    = f.label :measurement
    = f.text_field :measurement
  .field
    = f.label :container_type
    = f.select :container_type, Libation.container_types.keys
  .field
    = f.label :measurement_type
    = f.select :measurement_type, Libation.measurement_types.keys
  .field
    = f.label :country_made
    = f.text_field :country_made
  .field
    = f.label :company_name
    = f.text_field :company_name
  .field
    = f.label :libation_type
    = f.select :libation_type, Libation.libation_types.keys
  .field
    = f.label :website
    = f.text_field :website
  .actions = f.submit

app/views/libations/edit.html.slim
h1 Editing libation

== render 'form'

= link_to 'Show', @libation
'|
= link_to 'Back', libations_path

app/views/libations/index.html.slim
h1 Listing libations

table
  thead
    tr
      th Libation name
      th Measurement
      th Container type
      th Measurement type
      th Country made
      th Company name
      th Libation type
      th Website
      th
      th
      th

  tbody
    - @libations.each do |libation|
      tr
        td = libation.libation_name
        td = libation.measurement
        td = libation.container_type
        td = libation.measurement_type
        td = libation.country_made
        td = libation.company_name
        td = libation.libation_type
        td = libation.website
        td = link_to 'Show', libation
        td = link_to 'Edit', edit_libation_path(libation)
        td = link_to 'Destroy', libation, data: {:confirm => 'Are you sure?'}, :method => :delete

br

= link_to 'New Libation', new_libation_path

app/views/libations/new.html.slim
h1 New libation

== render 'form'

= link_to 'Back', libations_path

app/views/libations/show.html.slim
p#notice = notice

p
  strong Libation name:
  = @libation.libation_name
p
  strong Measurement:
  = @libation.measurement
p
  strong Container type:
  = @libation.container_type
p
  strong Measurement type:
  = @libation.measurement_type
p
  strong Country made:
  = @libation.country_made
p
  strong Company name:
  = @libation.company_name
p
  strong Libation type:
  = @libation.libation_type
p
  strong Website:
  = @libation.website

= link_to 'Edit', edit_libation_path(@libation)
'|
= link_to 'Back', libations_path

app/views/pages/about.html.erb
<% content_for :title do %>About<% end %>
<h3>About the Website</h3>
<p>
This web application was created with
<%= link_to('Rails Composer', 'http://railsapps.github.io/rails-composer/') %>
from the <%= link_to('RailsApps project', 'http://railsapps.github.io/') %>.
</p>

app/views/static_pages/about.html.slim
h1 About The Libation Database
h3 Libation History

p The year 2006 found me working in Hawaii. On the way to work was a large Japanese based store: Daiai. I believe that it has been sold and is now Don Quixote, go figure. Anyways, I liked the wide range of exotic foods and products for sale & visited often. One day as I walked down the drink aisle I came noticed some interesting beverages that I had never imagined before. I bought a few, one in particular was made of Aloe Vera! I liked them so much that I went back the next day and bought about $50 of different juices. Some cans had sparse english, others from all over Asia and others with great designs like a soda can that seemed to be brushed aluminum. I was hooked.

h3 The Word Libation

p The word Libation has a nice ring to it. At first I called it my Juice database. After a while I was trying other drinks that were not really juices, so I started calling it Beverages. I had that for a while but then decided that a better word was available. An old friend wanted to open up a joint called Libations & Comestibles, great almost forgotten words. I always liked that Libation word so I ended up choosing that, and thats my story and I'm sticking to it.

h3 Starting Out

p At first I just kept track on paper. At first this was okay, but after a while I decided to take some pictures because they were interesting and soon I had quite a number. To keep track of them all, I created a spreadsheet, after all I am a tech nerd. It kept growing and I added more data fields (strictly research) and it just kind of kept growing. It evolved to a point that I decided it was time to place the results in a db and of course that would also require a set of screens to access them.

p I started first to go for a PHP app because I was using the LAMP stack. Made some progress, but kept it as a local copy only and I was thinking of putting it online. I migrated to wanting to do it using Java. The PHP project was dropped as I started the Java coded project. After a while the Java project tapered off as interest waned, but I dumped the db I created and the photos kept piling up.

h3 Now its 2016

p Ten years later and its time to finally do this app, and I will be using Ruby/Rails. It'll be posted on Github, so the work will be in the open. Not sure all the details, but I have started and looking forward to seeing this thing working. Besides, I was still taking photos of the libations and now have quite a backlog.

h3 Technical notes

b User table
p Decided to have users, so others could add to the db. Wether I fully implement this or not is moot, I want to have this separation there in case I do.

b Libation table
p This table has the root info for each libation, my goal was to only list things that would not change.

b Detail table
p The idea for this table are the things that can vary. This is mostly the review of the libation, like its sweetness, with is subjective to each person/user.

p Decided that I would create a one-many relationship between the main <b>libation</b> entry and the <b>detail</b> entry. This way, if I wanted I could have others also add their detail information to a specific libation.

b Ratings
p There are many columns in the <b>detail</b> table to allow a rating of the libation. I chose as a scale for many ratings 0-5, because I think (for myself) that I can reasonably rate drinks with that accuracy, where as ten different levels, I feel I would be guessing more then I am now!

p 1 Jan 2016

app/views/static_pages/devlog.html.slim
h1 Development Log

b 5 Jan 2016
ul
  li Added enumeration for container, type or libation and weight measurement
  li Made home page a little nicer.

b 1 Jan 2016
ul
  li Added static pages
  li Added paperclip gem

b Dec 2015
ul
  li Set up app, using bootstrap
  li Using devise for authentication
  li Database setup
  li Admin panel setup

app/views/static_pages/help.html.slim
h1 Technical Information

p A libation record is comprised of two parts, a libation and a detail.
ol
  li The libation record that records the base (static) information of the libation.
  ul
    li This includes can weight, container type and product information etc.
  li The detail record that records the subjective information, based on the person sampling the libation.
  ul
    li This includes what the reviewer though of the taste, clolour, sweetness, etc.

p There is some information that is selected from a dropdown box, here they are:
h3 Libation Type
p This refers to the libation type, also specifying the db code used. Currently the options are:
ul
  li drink  1
  li juice 2
  li soda 3
  li tea 4
  li dairy 5
  li wine 6
  li beer 7
  li other 99

h3 Container Type
p This refers to the material used to create the container. Currently the options are:
ul
  li Aluminium 1
  li Glass 2
  li Plastic 3
  li Steel 4
  li Tetra 5
  li Cardboard 6
  li Other 7

h3 Measurement Type
p This refers to weight measurement type. Currently the options are:
ul
  li g - grams 1
  li l - litre 2
  li ml - millilitre 3
  li oz - ounces 4

h3 Ratings
p There are numerous ratings, like flavour, sweetness, can_art, etc. They are based and enforced to be a 0-5 scale.
ul
  li 0 being the least flavourful, least sweet, ugliest can art.
  li 2-3 being about neutral or average
  li 5 being the most flavourful, most sweet, prettiest can art.

h3 Images
p This is to be determined, but will specify a recommended range of picture quality requested. Also, it will be recommended that there will be pictures covering the front and all sides of the libation, plus anything extra or interesting that needs a second look. Such things as a unique lid, where the opening changes the look of the container.

h3 List of criteria
p There are many pieces of information that will be covered, and some need a little further explanation.

h5 Libation Record
p This information is mostly static, is listed on the container.
ul
  li Libation name - The name that is on the container.
  li Libation type - This is the type of libation, select from predetermined list.
  li Container type - This is the type of container, select from predetermined list.
  li Measurement - This is the weight, numbers only on the container,
  li Measurement type - This is the weight type (gm, oz, etc), select from predetermined list.
  li Country made - The container will often have the country where made.
  li Company name - The container will often have the company name.
  li Website - The container will often list a website.

h5 Detail Record
p The detail record contains the information that the reviewer will fill out, mostly after they have had the libation. There are ratings required (mentioned above) that are subjective.
ul
  li Date drank - When the libation was consumed.
  li Store_purchased - The store where the libation was purchased.
  li City purchased - The city where the libation was purchased.
  li Prov purchased - The province/state where the libation was purchased.
  li Country purchased - The country where the libation was purchased.
  li Colour - The colour of the libation.
  li pulp - Rating from 0-5 of how much pulp there was.
  li Can art - Rating from 0-5 of the art design on the can. 0=Boring 5=Excellent.
  li Can look - Rating from 0-5 of the look of the cans physical appearance. 0=Boring 5=Excellent.
  li Sweet - Rating from 0-5 of how sweet it was, 0=tart 5=Super sweet.
  li Juice - Percentage of juice in the libation. Listed on package.
  li Sip-giz - Rating from 0-5 of 0=Sip only to 5=Guzzle the thing.
  li Flavour - Rating from 0-5 of the flavour.
  li Buy again - Yes, no, or maybe.
  li Carbonated - Yes or no.
  li Filename - This will be an image of the libation. Want multiple sides.
  li Comments - Can be quite creative here, have fun.


Last updated, January 10, 2016

app/views/static_pages/home.html.slim
h1 StaticPages#home
p Find me in app/views/static_pages/home.html.slim

app/views/users/_user.html.erb
<td><%= link_to user.username, user %></td>
<td><%= link_to user.first_name, user %></td>
<td><%= link_to user.last_name, user %></td>
<td><%= link_to user.email, user %></td>

app/views/users/index.html.erb
<div class="container">
  <div class="row">
    <h3>Users</h3>
    <div class="column">
      <table class="table">
        <tbody>
          <% @users.each do |user| %>
            <tr>
              <%= render user %>
            </tr>
          <% end %>
        </tbody>
      </table>
    </div>
  </div>
</div>

app/views/users/show.html.erb
<h3>User</h3>
<p>Username: <%= @user.username if @user.username %></p>
<p>First name: <%= @user.first_name if @user.first_name %></p>
<p>Last name: <%= @user.last_name if @user.last_name %></p>
<p>Email: <%= @user.email if @user.email %></p>

app/views/visitors/index.html.erb
<h3>Libations</h3>
<p>We currently have <%= Libation.count %> libations</p>
<p>More are on their way.</p>
<p><%= link_to 'Random libation', libation_path(@rnd) %> </p>